const articles = [
	{
		name: 'The Importance of Regular Therapy Supervision',
		slug: 'the-importance-of-regular-therapy-supervision',
		image: '/article_1.webp',
		author: "Kathryn O'Reilly",
		date: '25 June 2022',
		h1: 'The Importance of Regular Therapy Supervision',
		p1: 'As a therapist, you are committed to providing the highest level of care to your clients. One way to ensure that you are able to do this is by participating in regular therapy supervision. Therapy supervision is the process of receiving guidance and support from an experienced therapist while working with clients. It can help you improve your skills, enhance your knowledge, and better serve your clients.',
		h2: 'How does therapy supervision help me?',
		p2: 'The benefits of therapy supervision go beyond just improving your clinical work. It can also provide a supportive environment for you to reflect on your practice, share your challenges and successes, and receive feedback from an experienced therapist. This can be particularly helpful for therapists who are new to the field or who are seeking to expand their knowledge and skills.',
		h3: 'But how do you go about finding a therapy supervisor?',
		p3: 'There are a few different options to consider. You can ask for recommendations from colleagues, search online directories or professional organizations, or reach out to therapists who specialize in your area of interest. It is important to do your research and find a supervisor who is a good fit for your needs and goals. When choosing a therapy supervisor, it is important to consider their experience and qualifications, as well as their areas of expertise and focus. It can also be helpful to consider the type of supervision you prefer, such as group supervision or individual supervision. It is also a good idea to ask for references or speak with other therapists who have worked with the supervisor to get a sense of their style and approach. Finally, it is important to find a supervisor who you feel comfortable working with and who aligns with your values and goals as a therapist.',
		h4: 'Is online supervision an option?',
		p4: 'Online therapy supervision is also an option for therapists who may not have access to supervision in their local area or who have busy schedules. Online supervision can be provided through video conferencing or phone calls, and it can be a convenient way to receive guidance and support from an experienced therapist.',
		h5: 'Cost considerations',
		p5: 'The cost of therapy supervision can vary depending on the supervisors experience and location. Many supervisors offer discounts for students or therapists who are just starting their practices. It is important to consider your budget and find a supervisor who fits your needs and financial constraints.',
		h6: 'Final thoughts',
		p6: 'Overall, regular therapy supervision can be an invaluable resource for therapists. It can help you grow and develop as a therapist, enhance your knowledge and skills, and provide a supportive environment for reflection and growth. So if you want to be the best therapist you can be and provide the highest level of care to your clients, consider investing in regular therapy supervision.',
	},
	{
		name: 'Article 2',
		slug: 'article-2',
		image: '/article_2.webp',
		author: "Kathryn O'Reilly",
		date: '25 July 2022',
		h1: 'Article 2 Title',
		p1: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut cumque soluta? Porro quos saepe ratione deleniti dicta, fugiat odio architecto dolores voluptas officiis, ipsum veniam? Ullam, et. Itaque laborum molestias unde maiores expedita eius laudantium, nulla aut animi consequuntur ex in iusto repellat! Explicabo vero nam voluptatibus quos molestiae',
		h2: 'Heading 2',
		p2: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut cumque soluta? Porro quos saepe ratione deleniti dicta, fugiat odio architecto dolores voluptas officiis, ipsum veniam? Ullam, et. Itaque laborum molestias unde maiores expedita eius laudantium, nulla aut animi consequuntur ex in iusto repellat! Explicabo vero nam voluptatibus quos molestiae',
		h3: 'Heading 2',
		p3: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut cumque soluta? Porro quos saepe ratione deleniti dicta, fugiat odio architecto dolores voluptas officiis, ipsum veniam? Ullam, et. Itaque laborum molestias unde maiores expedita eius laudantium, nulla aut animi consequuntur ex in iusto repellat! Explicabo vero nam voluptatibus quos molestiae',
		h4: 'Heading 2',
		p4: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut cumque soluta? Porro quos saepe ratione deleniti dicta, fugiat odio architecto dolores voluptas officiis, ipsum veniam? Ullam, et. Itaque laborum molestias unde maiores expedita eius laudantium, nulla aut animi consequuntur ex in iusto repellat! Explicabo vero nam voluptatibus quos molestiae',
		h5: 'Heading 2',
		p5: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut cumque soluta? Porro quos saepe ratione deleniti dicta, fugiat odio architecto dolores voluptas officiis, ipsum veniam? Ullam, et. Itaque laborum molestias unde maiores expedita eius laudantium, nulla aut animi consequuntur ex in iusto repellat! Explicabo vero nam voluptatibus quos molestiae',
		h6: 'Heading 2',
		p6: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut cumque soluta? Porro quos saepe ratione deleniti dicta, fugiat odio architecto dolores voluptas officiis, ipsum veniam? Ullam, et. Itaque laborum molestias unde maiores expedita eius laudantium, nulla aut animi consequuntur ex in iusto repellat! Explicabo vero nam voluptatibus quos molestiae',
	},
	{
		name: 'Article 3',
		slug: 'article-3',
		image: '/article_3.webp',
		author: "Kathryn O'Reilly",
		date: '25 August 2022',
		h1: 'Article 3 Title',
		p1: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut cumque soluta? Porro quos saepe ratione deleniti dicta, fugiat odio architecto dolores voluptas officiis, ipsum veniam? Ullam, et. Itaque laborum molestias unde maiores expedita eius laudantium, nulla aut animi consequuntur ex in iusto repellat! Explicabo vero nam voluptatibus quos molestiae',
		h2: 'Heading 2',
		p2: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut cumque soluta? Porro quos saepe ratione deleniti dicta, fugiat odio architecto dolores voluptas officiis, ipsum veniam? Ullam, et. Itaque laborum molestias unde maiores expedita eius laudantium, nulla aut animi consequuntur ex in iusto repellat! Explicabo vero nam voluptatibus quos molestiae',
		h3: 'Heading 2',
		p3: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut cumque soluta? Porro quos saepe ratione deleniti dicta, fugiat odio architecto dolores voluptas officiis, ipsum veniam? Ullam, et. Itaque laborum molestias unde maiores expedita eius laudantium, nulla aut animi consequuntur ex in iusto repellat! Explicabo vero nam voluptatibus quos molestiae',
		h4: 'Heading 2',
		p4: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut cumque soluta? Porro quos saepe ratione deleniti dicta, fugiat odio architecto dolores voluptas officiis, ipsum veniam? Ullam, et. Itaque laborum molestias unde maiores expedita eius laudantium, nulla aut animi consequuntur ex in iusto repellat! Explicabo vero nam voluptatibus quos molestiae',
		h5: 'Heading 2',
		p5: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut cumque soluta? Porro quos saepe ratione deleniti dicta, fugiat odio architecto dolores voluptas officiis, ipsum veniam? Ullam, et. Itaque laborum molestias unde maiores expedita eius laudantium, nulla aut animi consequuntur ex in iusto repellat! Explicabo vero nam voluptatibus quos molestiae',
		h6: 'Heading 2',
		p6: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut cumque soluta? Porro quos saepe ratione deleniti dicta, fugiat odio architecto dolores voluptas officiis, ipsum veniam? Ullam, et. Itaque laborum molestias unde maiores expedita eius laudantium, nulla aut animi consequuntur ex in iusto repellat! Explicabo vero nam voluptatibus quos molestiae',
	},
];

export default articles;
