const articles = [
  {
    name: "Article 1",
    slug: "article-1",
    image: "/article_1.webp",
    author: "Kathryn O'Reilly",
    date: "25 June 2022",
    h1: "Article 1 Title",
    p1: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut cumque soluta? Porro quos saepe ratione deleniti dicta, fugiat odio architecto dolores voluptas officiis, ipsum veniam? Ullam, et. Itaque laborum molestias unde maiores expedita eius laudantium, nulla aut animi consequuntur ex in iusto repellat! Explicabo vero nam voluptatibus quos molestiae",
    h2: "Heading 2",
    p2: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut cumque soluta? Porro quos saepe ratione deleniti dicta, fugiat odio architecto dolores voluptas officiis, ipsum veniam? Ullam, et. Itaque laborum molestias unde maiores expedita eius laudantium, nulla aut animi consequuntur ex in iusto repellat! Explicabo vero nam voluptatibus quos molestiae",
    h3: "Heading 2",
    p3: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut cumque soluta? Porro quos saepe ratione deleniti dicta, fugiat odio architecto dolores voluptas officiis, ipsum veniam? Ullam, et. Itaque laborum molestias unde maiores expedita eius laudantium, nulla aut animi consequuntur ex in iusto repellat! Explicabo vero nam voluptatibus quos molestiae",
    h4: "Heading 2",
    p4: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut cumque soluta? Porro quos saepe ratione deleniti dicta, fugiat odio architecto dolores voluptas officiis, ipsum veniam? Ullam, et. Itaque laborum molestias unde maiores expedita eius laudantium, nulla aut animi consequuntur ex in iusto repellat! Explicabo vero nam voluptatibus quos molestiae",
    h5: "Heading 2",
    p5: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut cumque soluta? Porro quos saepe ratione deleniti dicta, fugiat odio architecto dolores voluptas officiis, ipsum veniam? Ullam, et. Itaque laborum molestias unde maiores expedita eius laudantium, nulla aut animi consequuntur ex in iusto repellat! Explicabo vero nam voluptatibus quos molestiae",
    h6: "Heading 2",
    p6: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut cumque soluta? Porro quos saepe ratione deleniti dicta, fugiat odio architecto dolores voluptas officiis, ipsum veniam? Ullam, et. Itaque laborum molestias unde maiores expedita eius laudantium, nulla aut animi consequuntur ex in iusto repellat! Explicabo vero nam voluptatibus quos molestiae",
  },
  {
    name: "Article 2",
    slug: "article-2",
    image: "/article_2.webp",
    author: "Kathryn O'Reilly",
    date: "25 July 2022",
    h1: "Article 2 Title",
    p1: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut cumque soluta? Porro quos saepe ratione deleniti dicta, fugiat odio architecto dolores voluptas officiis, ipsum veniam? Ullam, et. Itaque laborum molestias unde maiores expedita eius laudantium, nulla aut animi consequuntur ex in iusto repellat! Explicabo vero nam voluptatibus quos molestiae",
    h2: "Heading 2",
    p2: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut cumque soluta? Porro quos saepe ratione deleniti dicta, fugiat odio architecto dolores voluptas officiis, ipsum veniam? Ullam, et. Itaque laborum molestias unde maiores expedita eius laudantium, nulla aut animi consequuntur ex in iusto repellat! Explicabo vero nam voluptatibus quos molestiae",
    h3: "Heading 2",
    p3: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut cumque soluta? Porro quos saepe ratione deleniti dicta, fugiat odio architecto dolores voluptas officiis, ipsum veniam? Ullam, et. Itaque laborum molestias unde maiores expedita eius laudantium, nulla aut animi consequuntur ex in iusto repellat! Explicabo vero nam voluptatibus quos molestiae",
    h4: "Heading 2",
    p4: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut cumque soluta? Porro quos saepe ratione deleniti dicta, fugiat odio architecto dolores voluptas officiis, ipsum veniam? Ullam, et. Itaque laborum molestias unde maiores expedita eius laudantium, nulla aut animi consequuntur ex in iusto repellat! Explicabo vero nam voluptatibus quos molestiae",
    h5: "Heading 2",
    p5: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut cumque soluta? Porro quos saepe ratione deleniti dicta, fugiat odio architecto dolores voluptas officiis, ipsum veniam? Ullam, et. Itaque laborum molestias unde maiores expedita eius laudantium, nulla aut animi consequuntur ex in iusto repellat! Explicabo vero nam voluptatibus quos molestiae",
    h6: "Heading 2",
    p6: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut cumque soluta? Porro quos saepe ratione deleniti dicta, fugiat odio architecto dolores voluptas officiis, ipsum veniam? Ullam, et. Itaque laborum molestias unde maiores expedita eius laudantium, nulla aut animi consequuntur ex in iusto repellat! Explicabo vero nam voluptatibus quos molestiae",
  },
  {
    name: "Article 3",
    slug: "article-3",
    image: "/article_3.webp",
    author: "Kathryn O'Reilly",
    date: "25 August 2022",
    h1: "Article 3 Title",
    p1: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut cumque soluta? Porro quos saepe ratione deleniti dicta, fugiat odio architecto dolores voluptas officiis, ipsum veniam? Ullam, et. Itaque laborum molestias unde maiores expedita eius laudantium, nulla aut animi consequuntur ex in iusto repellat! Explicabo vero nam voluptatibus quos molestiae",
    h2: "Heading 2",
    p2: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut cumque soluta? Porro quos saepe ratione deleniti dicta, fugiat odio architecto dolores voluptas officiis, ipsum veniam? Ullam, et. Itaque laborum molestias unde maiores expedita eius laudantium, nulla aut animi consequuntur ex in iusto repellat! Explicabo vero nam voluptatibus quos molestiae",
    h3: "Heading 2",
    p3: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut cumque soluta? Porro quos saepe ratione deleniti dicta, fugiat odio architecto dolores voluptas officiis, ipsum veniam? Ullam, et. Itaque laborum molestias unde maiores expedita eius laudantium, nulla aut animi consequuntur ex in iusto repellat! Explicabo vero nam voluptatibus quos molestiae",
    h4: "Heading 2",
    p4: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut cumque soluta? Porro quos saepe ratione deleniti dicta, fugiat odio architecto dolores voluptas officiis, ipsum veniam? Ullam, et. Itaque laborum molestias unde maiores expedita eius laudantium, nulla aut animi consequuntur ex in iusto repellat! Explicabo vero nam voluptatibus quos molestiae",
    h5: "Heading 2",
    p5: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut cumque soluta? Porro quos saepe ratione deleniti dicta, fugiat odio architecto dolores voluptas officiis, ipsum veniam? Ullam, et. Itaque laborum molestias unde maiores expedita eius laudantium, nulla aut animi consequuntur ex in iusto repellat! Explicabo vero nam voluptatibus quos molestiae",
    h6: "Heading 2",
    p6: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias ut cumque soluta? Porro quos saepe ratione deleniti dicta, fugiat odio architecto dolores voluptas officiis, ipsum veniam? Ullam, et. Itaque laborum molestias unde maiores expedita eius laudantium, nulla aut animi consequuntur ex in iusto repellat! Explicabo vero nam voluptatibus quos molestiae",
  },
];

export default articles;
